### ISSUE TITLE
Datenerfassung mittels Batchfile

### ISSUE THREAD

**Issue by patricksteinhaeusl** [patricksteinhaeusl/Bachelorarbeit#17]
Die Datenerfassung wird aktuell im Javacode erledigt und sollte besser als MongoDB Batch File erledigt werden.

**Comment by rustaska** [comment]
Vorschlag: Daten als JSON hinterlegen und mittels Batchfile die Daten parsen und in die DB speisen. So können die Daten auch gleich in der Anwendung verwendet werden und nicht nur im Zusammenhang mit Docker. -> Loose Kopplung
